### ISSUE TITLE
MCP3208 max. clock frequency

### ISSUE THREAD

**Issue by fivdi** [derekmolloy/exploringrpi#1]
According to the timing parameters on page 3 of the [MCP3208 datasheet](http://ww1.microchip.com/downloads/en/DeviceDoc/21298e.pdf) the max. clock frequency is 2.0MHz at VDD = 5v and 1.0MHz at VDD = 2.7V. At 3.3V on the Raspberry Pi the max. clock frequency will be somewhere in between but probably closer to 1MHz than 2MHz. The TMP36 sample program on page 423 [sets the clock frequency to 5MHz](https://github.com/derekmolloy/exploringrpi/blob/master/chp10/tmp36/tmp36.cpp#L16).

**Comment by derekmolloy** [comment]
Thanks for that. I have updated the clock frequency to 1MHz.

**Comment by fivdi** [comment]
> Thanks for that.

You're welcome.

It looks better now.
